DROP TYPE IF EXISTS studio_user_status CASCADE;
DROP TYPE IF EXISTS studio_user_roles CASCADE;

DROP TABLE IF EXISTS song_genres CASCADE;
DROP TABLE IF EXISTS studio_songs CASCADE;
DROP TABLE IF EXISTS studio_users CASCADE;
DROP TABLE IF EXISTS artiste CASCADE;
DROP TABLE IF EXISTS song_ratings CASCADE;
DROP TABLE IF EXISTS song_reviews CASCADE;
DROP TABLE IF EXISTS review_comments CASCADE;